import { ImprovedRenderEventEmitter, EventHandlerReturnValue } from "@jaisocx/event-emitter";
import { TemplateRenderer } from "@jaisocx/template-renderer";
import { ITreeRenderRetValue, IRenderTemplateRendererData, ITreeAdapter } from "./Types.js";
import { TreeConf } from "./TreeConf.js";
import { TreeInterface } from "./TreeInterface.js";
export declare class Tree extends ImprovedRenderEventEmitter implements TreeInterface {
    debug: boolean;
    mainHtmlNodeId: any;
    mainHolderHtmlNode: HTMLElement | null;
    url: any | null;
    data: any | null;
    conf: TreeConf;
    subtreeLength: number;
    subtreeLengthDeep: number;
    templateRenderer: TemplateRenderer;
    contextMenuJSClass: any;
    renderingMode: number;
    nodesWithIcons: boolean;
    nodesOpenedMode: number;
    isModifiable: boolean;
    dataTypesCssClassesEnabled: boolean;
    adapter: ITreeAdapter;
    constructor();
    setDebug(debug: boolean): Tree;
    setNodesWithIcons(withIcons: boolean): Tree;
    setNodesOpenedMode(openedMode: number): Tree;
    setUrl(url: any | null): Tree;
    setMainHtmlNodeId(mainHtmlNodeId: any): Tree;
    setConf(conf: TreeConf): Tree;
    setModifiable(isModifiable: boolean): Tree;
    setRenderingMode(mode: number): Tree;
    setDataTypesCssClassesEnabled(dataTypesCssEnabled: boolean): Tree;
    load(url: any | null): Tree;
    adaptRenderingModeSubcalls(): void;
    reRender(): Tree;
    render(nodes: any): Tree;
    checkDataNodeSubtree(node: any): {
        isArray: number;
        subtreeNodeDataType: number;
        subtreeNodeDataTypeString: any;
        hasSubtree: boolean;
        subtreeJsonNodes: any;
        objectKeys: any[] | null;
    };
    renderSubtree(isArray: number, subtreeNodes: any, flatNodeHolderClone: any, objectKeys: any[] | null, subtreeHtmlHolder: HTMLElement): number;
    renderSubtreeCallback(_isArray: number, loopCounter: number, loopPropertyValue: any, loopPropertyKey: any, _arrayOrObject: any, previousCallbackResult: number | null, callbackPayload: any): number;
    renderOneTreeNode(node: any, nodePosition: number, nodeKey: any, flatNodeHolderClone: any, holder: HTMLElement): ITreeRenderRetValue;
    updateDataNodeIdAndPath(node: any, nodePosition: number, nodeKey: any, flatNodeHolderClone: any, _holder: HTMLElement): any;
    getTreeDataByJPath(jPathArray: any[]): any;
    getSubtreeNodeToRender(_loopPropertyValue: any, _loopPropertyKey: any): any;
    getDataForRendering(_node: any, _flatNodeClone: any, _dataTypeString: any, _hasSubtree: boolean): IRenderTemplateRendererData;
    getTreeNodeCssClasses(_dataType: any, _node: any): any;
    addJSTreeEventListener(eventName: any, eventHandler: (eventName: any, payload: any) => EventHandlerReturnValue | null | undefined | void): Tree;
    addJSTreeEventListeners(): Tree;
    initializeCustomJsTreeImprovedEventHandler(jsTreeEventName: any, customEventHandler: any): (eventPayload: any) => void;
    openButtonClickHandler(eventPayload: any): void;
    treeNodeLableClickHandler(_eventPayload: any): void;
    getInModeConfDataNodeIsTreeItem(node: object): boolean;
    escapeHTMLForAttribute(str: any): any;
    unescapeHTMLFromAttribute(str: any | undefined): any;
    getTreeHtmlNodeDatasetJson(htmlNode: HTMLElement | null): any;
}
//# sourceMappingURL=Tree.d.ts.map