import { TextEncoder } from "util";
import { Keywords_JsConstants } from "./Keywords_JsConstants.js";
export declare class BitbufKeywords_JsConstants extends Keywords_JsConstants {
    #private;
    _textEncoder: TextEncoder;
    constructor();
    getBitbuf_Js_Keyword_Import(): Uint8Array;
    getBitbuf_Js_Keyword_Export(): Uint8Array;
    getBitbuf_Js_Keyword_From(): Uint8Array;
    getBitbuf_Js_Keyword_Default(): Uint8Array;
    getBitbuf_Js_Keyword_Const(): Uint8Array;
    getBitbuf_Js_Keyword_Let(): Uint8Array;
    getBitbuf_Js_Keyword_Var(): Uint8Array;
    getBitbuf_Js_Keyword_Function(): Uint8Array;
    getBitbuf_Js_Keyword_Return(): Uint8Array;
    getBitbuf_Js_Keyword_If(): Uint8Array;
    getBitbuf_Js_Keyword_Else(): Uint8Array;
    getBitbuf_Js_Keyword_For(): Uint8Array;
    getBitbuf_Js_Keyword_While(): Uint8Array;
    getBitbuf_Js_Keyword_Try(): Uint8Array;
    getBitbuf_Js_Keyword_Catch(): Uint8Array;
    getBitbuf_Js_Keyword_Finally(): Uint8Array;
    getBitbuf_Js_Keyword_New(): Uint8Array;
    getBitbuf_Js_Keyword_Class(): Uint8Array;
    getBitbuf_Js_Keyword_Extends(): Uint8Array;
    getBitbuf_Js_Keyword_Super(): Uint8Array;
    getBitbuf_Js_Keyword_This(): Uint8Array;
    getBitbuf_Js_Keyword_Null(): Uint8Array;
    getBitbuf_Js_Keyword_True(): Uint8Array;
    getBitbuf_Js_Keyword_False(): Uint8Array;
    getBitbuf_Js_Token_StatementFinish(): Uint8Array;
    getBitbuf_Js_Token_Block_Open(): Uint8Array;
    getBitbuf_Js_Token_Block_Close(): Uint8Array;
    getBitbuf_Js_Token_Paren_Open(): Uint8Array;
    getBitbuf_Js_Token_Paren_Close(): Uint8Array;
    getBitbuf_Js_Token_Array_Open(): Uint8Array;
    getBitbuf_Js_Token_Array_Close(): Uint8Array;
    getBitbuf_Js_Token_Object_Open(): Uint8Array;
    getBitbuf_Js_Token_Object_Close(): Uint8Array;
    getBitbuf_Js_Token_MethodArgs_Start(): Uint8Array;
    getBitbuf_Js_Token_MethodArgs_Finish(): Uint8Array;
    getBitbuf_Js_Token_MethodArgs_Delimiter(): Uint8Array;
    getBitbuf_Js_Token_Assign(): Uint8Array;
    getBitbuf_Js_Token_Arrow(): Uint8Array;
    getBitbuf_Js_Token_ArrowFunction_Delimiter(): Uint8Array;
    getBitbuf_Js_Token_ClassAndProperty_Delimiter(): Uint8Array;
    getBitbuf_Js_Token_ClassAndMethod_Delimiter(): Uint8Array;
    getBitbuf_Js_Token_Typescript_Datatype_Delimiter(): Uint8Array;
}
//# sourceMappingURL=BitbufKeywords_JsConstants.d.ts.map