export declare class SymbolConstants {
    #private;
    constructor();
    getCharcodeSymbol(inSymbol: string): number;
    getQuoteDouble(): string;
    getQuoteSingle(): string;
    getQuoteAlt(): string;
    getBraceRoundOpen(): string;
    getBraceRoundClose(): string;
    getBraceTriangleOpen(): string;
    getBraceTriangleClose(): string;
    getBraceSquareOpen(): string;
    getBraceSquareClose(): string;
    getBraceFigureOpen(): string;
    getBraceFigureClose(): string;
    getColon(): string;
    getSemicolon(): string;
    getPoint(): string;
    getComma(): string;
    getDash(): string;
    getUnderscore(): string;
    getSlash(): string;
    getSlashUpwards(): string;
    getDollar(): string;
    getSymbol_Hashtag(): string;
    getSymbol_PERCENTS(): string;
    getAmpersand(): string;
    getTilde(): string;
    getDach(): string;
    getEquality(): string;
    getAddition(): string;
    getExclamation(): string;
    getQuestion(): string;
    getSymbolBackgroundColor(): string;
    getSymbolNumber_0_Zero(): string;
    getSymbolNumber_1_One(): string;
    getSymbolNumber_2_Two(): string;
    getSymbolNumber_3_Three(): string;
    getSymbolNumber_4_Four(): string;
    getSymbolNumber_5_Five(): string;
    getSymbolNumber_6_Six(): string;
    getSymbolNumber_7_Seven(): string;
    getSymbolNumber_8_Eight(): string;
    getSymbolNumber_9_Nine(): string;
    getNumber_0_Zero(): number;
    getNumber_1_One(): number;
    getNumber_2_Two(): number;
    getNumber_3_Three(): number;
    getNumber_4_Four(): number;
    getNumber_5_Five(): number;
    getNumber_6_Six(): number;
    getNumber_7_Seven(): number;
    getNumber_8_Eight(): number;
    getNumber_9_Nine(): number;
}
//# sourceMappingURL=SymbolConstants.d.ts.map